### ISSUE TITLE
Revealing Section Issues with IE

### ISSUE THREAD

**Issue by AllanHall** [CodyHouse/cd-revealing-hero-changelog#1]
Hello! We are running into an issue with the Revealing Section on Internet Explorer. 
The issue is on this snippet on line 106 of the _1_revealing-section.js file:
`document.fonts.onloadingdone = function (fontFaceSetEvent) {
      doneResizing();
    };`

document.fonts isn't supported on IE https://developer.mozilla.org/en-US/docs/Web/API/Document/fonts so we're having issues with the reveal effect.

Any help on this would be greatly appreciated. Thank you!

**Comment by claudia-romano** [comment]
Hi there,
you should try adding a check to see if document.fonts is supported:
```
if(document.fonts) {
  document.fonts.onloadingdone = function (fontFaceSetEvent) {
    doneResizing();
  };
}
```
This should fix your issue. 

We'll make sure to update the component code as well. Cheers!

**Comment by claudia-romano** [comment]
We have updated the component to include a check for document.fonts:
https://codyhouse.co/ds/components/app/revealing-hero

Cheers!
